### ISSUE TITLE
Classic diagnostic settings enable and disable through terraform

### ISSUE THREAD

**Issue by raswinraaj** [claranet/terraform-azurerm-storage-account#8]
### Description

I know there is a resource azurerm_monitor_diagnostic_setting for enabling or disabling diagnostic settings. But this is for the new Diagnostic settings. Can you please let me know how to enable/disable the Classic diagnostic logs ? Below is the image of what I am looking for?
![image](https://github.com/claranet/terraform-azurerm-storage-account/assets/50330414/b668d486-43f4-434e-b218-db526d6b63c0)

**Comment by BzSpi** [comment]
Hello,

This can be done in the [azurerm_storage_account resource](https://registry.terraform.io/providers/hashicorp/azurerm/latest/docs/resources/storage_account#delete) with `metrics` and `logging` blocks. However, this is not supported by our module and will never be since this is a deprecated feature.

If you really want to do this and use our module, you can give it a try with the azapi provider but you may encounter issues.
